[plugin]
id = "solace.jms-compiler-plugin"
class = "io.ballerina.lib.solace.jms.compiler.SolaceJmsCompilerPlugin"

[[dependency]]
path = "../compiler-plugin/build/libs/solace.jms-compiler-plugin-0.2.0-SNAPSHOT.jar"
